language: node_js

env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest

node_js:
    - 'node'
    - '10'

sudo: false

git:
    submodules: false

before_script:
    - npm install
script:
    - npm run build
    - npm run test
